### PR TITLE
Added early bird ticket link

### PR DESCRIPTION
**Pull request by garrows**

### CODE REVIEW

**Comment by iamkevinv** [comment]
First! 🤓

**Comment by developersteve** [comment]
Second first

**Comment by AnnaGerber** [comment]
🎉 woohoo 🎈 🎉 👏

**Comment by iamkevinv** [comment]
You **_fib_** @developersteve! - @AnnaGerber is second-first!
Invoice 0000001 (🥇 @iamkevinv) and 0000002 (🥈 @AnnaGerber) respectively! Tee heeee! 🤡

**Comment by developersteve** [comment]
haha touche

**Comment by garrows** [comment]
Haha congrats @iamkevinv and @annagerber.

**Pull request merged**
