### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by twalve**
Adding the base structure of the Sponsors page to learn the Next.js ropes.

Is it just me or do they look something like a noose? :P

### CODE REVIEW

**Comment by twalve** [comment]
Are the conflicts normal and what is used to trigger the build process? Surely not??

**Comment by garrows** [comment]
Conflicts aren't normal. It'll need a rebase. I can fix it up this afternoon.
Thanks for putting this together!!! Stellar effort.

**Comment by garrows** [comment]
Thanks @twalve! I think all the conflicts were caused by deleting the docs directory. It's messy to commit the build files but its what we have to do to use github pages. I I'll probably move to a VM next year and/or setup some CI.

**Comment by twalve** [comment]
I hadn't deleted it, only `gitignored` it.

I have another sponsor for this page so will update and try again 🗡 

Thanks for the merge

**Pull request merged**
