### PR TITLE
Added bus invoices. Due 3rd Aug

### PR DESCRIPTION
**Pull request by garrows**
Hey @DamonOehlman 
These are due on the 3rd of Aug. Please merge when you have paid. 

Mozilla is kindly sponsoring $1500 toward the busses too!
@marcosc here are the invoices for you.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
@garrows Looks pretty good, though we've got 5 x booking confirmations (without any payment information).  Just wondering if we could do something like the following, depending on whether Mozilla AU can claim GST input credits (or all the funds are paid from a global company in which case GST doesn't apply anyway).

Create two invoices:

- The first covering 3 of the bookings (totalling $1800 ex GST).  @marcosc do you think you could twist an arm or two to get to $1800?  If not, I can probably do a transfer of the additional $300 to the appropriate place in moz.

- A second invoice for 2 of the bookings (totalling $1200 ex GST, $1320 inc).  I'll make the transfer for the $1320 across to the account for that.

Don't make contact back with the bus company yet, wait for Marcos to come back with what we can do.  I'm keen for Mozilla to get an invoice that is useful for them though as generally that makes everyone's lives easier from an internal accounting perspective.

**Comment by garrows** [comment]
I've replied and asked for the account details (they said it was on the invoices but obviously its not) and I've requested the invoice groupings. Of course I did this before reading all the way through your email to the bit that says don't contact them yet :weary:

**Comment by marcoscaceres** [comment]
Sorry, I can't get additional funds:(

**Comment by marcoscaceres** [comment]
Just noting that making the invoice for $1800 and sending the $300 difference back to Mozilla would work.

**Comment by garrows** [comment]
Response from bus company
> What I have sent to you are booking confirmations.  Tax invoices will be sent to you separately. Our accounts department is closed on Wednesdays, so will be emailed to you tomorrow, together with our banking details.  I will make sure that you receive 2 invoices as requested.

**Comment by marcoscaceres** [comment]
👌

**Comment by DamonOehlman** [comment]
@garrows @marcoscaceres That all sounds good to me - thanks :)

**Comment by garrows** [comment]
Account Name : SITA HOLDINGS PTY LTD
Name of Bank : CBA
BSB : 063 – 010
ACCOUNT : 1259 6023

**Comment by garrows** [comment]
I've removed the booking confirmations and replaced it with the actual invoices. Pay to 
Account Name : SITA HOLDINGS PTY LTD
Name of Bank : CBA
BSB : 063 – 010
ACCOUNT : 1259 6023

**Comment by garrows** [comment]
I've updated the PR with the split invoice.

**Comment by DamonOehlman** [comment]
Thanks Glen - I'll transfer $1980 to payout invoice no. 14039 now.

**Comment by garrows** [comment]
@marcoscaceres can you confirm that Mozilla has paid their share?

**Comment by marcoscaceres** [comment]
Confirmed. Got an email a few days ago that the request for payment had gone out to our accounting department. 💸

I can also ping the bus company and double check they got paid.

**Comment by garrows** [comment]
Awesome. Thanks @marcoscaceres

**Pull request merged**
