### PR TITLE
Food, Drinks & Misc Receipts

### PR DESCRIPTION
**Pull request by garrows**
Here is the first bit of shopping Will do another on Saturday afternoon. 

Please reimburse to
BSB 484799
Acc No. 072015536
$1,402.36

Cheers @DamonOehlman

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Hey Glen - can you let me know how we came out with the transfer for the food alcohol float please so I can reconcile everything please?  Thanks mate :)

**Comment by garrows** [comment]
So adding everything up we are still owed about $3519.20 but I still need to get all the receipts together and waiting on things like car hire deposit being refunded and such. I'll just update this one so its not done in drips and drabs for you.

**Comment by garrows** [comment]
Here's the final list @DamonOehlman. 

Expense | Cost
------------- |-------------
woolworths online | 1402.36
ecohart sunshine (projector hire) | 860
kmart | 25.6
coles | 40.75
coles | 6
cellabrations | 493.5
akarba party hire (heaters, lecterns)  | 990
target | 2
dan murpheys | 894.1
woolworths | 164.77
woolworths | 198.03
dan murpheys | 805.26
car hire | 212.18
hotel jeff (for network setup) | 272.36
hotel glen  | 252.11
refund akarba party hire (unused gas) | -90
refund woolworths | -95.25
Cash advance from CampJS | -3500
Total owed | 2933.77

**Comment by DamonOehlman** [comment]
Cool mate - thanks.  I'll put a transfer through for that tomorrow (along with the second part to the venue payment).

**Comment by DamonOehlman** [comment]
Paid.  Assuming that this is the last payment, I think you can be pretty proud of yourself for managing the budget glen.  We didn't accrue a surplus on this event, but the net loss was only $456.34 which is a mighty fine effort.

**Comment by garrows** [comment]
Thanks for crunching the numbers @DamonOehlman. I've still got to bill FunCaptcha for drink sponsorship so that'll put us in surplus (just).

**Pull request closed without merging**
