### PR TITLE
Add ProjectorHireMelbourne.com.au quote

### PR DESCRIPTION
**Pull request by thissophie**

### CODE REVIEW

**Comment by garrows** [comment]
Thanks @thepatrick. We'll have to get delivery. Can you check with them when we pay if it's delivered? 
I'm waiting to hear back from the venue if we need anything in the main hall or not too.

**Comment by thissophie** [comment]
@garrows we pay when it is delivered - either cash or eftpos machine (eftpos, visa or mastercard)

I'll get the delivery locked down. What time will you (or whoever can pay) be on site?

**Comment by garrows** [comment]
Cheers. Can you get them delivered at 12pm Friday?

**Comment by thissophie** [comment]
I asked - he can't do 12pm. Can do 9am, but asked latest time (I said 4pm).

I can probably get there by 10:30am (if the afternoon option isn't workable, but that is), but I'm not sure what the earliest time we can get stuff delivered to the camp is (and ignoring figuring out how to pay him)

**Comment by thissophie** [comment]
Delivery will be 2-3.

**Pull request merged**
